# 异常
### 异常的概念
##### 就是程序运行中出现的不正常的情况，是java提供的用于处理程序中错误的一种机制。

### 异常的由来
##### 问题也是现实生活中的一个具体的事物,也可以通过java的类的形式进行描述,并封装成对象，异常就是java对不正常情况描述后的对象体现.

### 异常继承体系图
![Java Exception类关系图](http://image.lxway.com/upload/2/da/2da20230b3ae8a577b62ba839c8a999a.jpg)

异常的继承结构:基类为`Throwable，Error`和`Exception`继承`Throwable`,`RuntimeException`和`IOException`等继承`Exception`,具体的`RuntimeException`继承`RuntimeException`	。

###  异常的分类

##### Error：对于严重的问题,java通过`Error`类进行描述（如java虚拟机生成并抛出异常，动态链接失败，虚拟机错误等），而且对于Error一般不编写针对性的代码对其进行处理。

##### Exception：对于非严重的,java通过`Exception`类进行描述.对于Exception可以使用针对性的处理方式进行处理.

##### Runtime Exception: `Exception`的子类，当出现这样的异常时，总是由虚拟机接管。比如：我们从来没有人去处理过NullPointerException异常，它就是运行时异常，并且这种异常还是最常见的异常之一。

`Runtime Exception` 和 `Exception` 的区别：
- Exception：在程序中必须使用`try...catch`进行处理。
- RuntimeException：可以不使用`try...catch`进行处理，但是如果有异常产生，则异常将由JVM进行处理。

###   自定义异常

创建`Exception`或者`RuntimeException`的子类即可得到一个自定义的异常类。例如:  
```java
 public class MyException extends Exception{   
 	public MyException(){}   
	public MyException(String smg){  
	   super(smg);   
	 }   
}

```
用`throws`声明方法可能抛出自定义的异常，并用`throw`语句在适当的地方抛出自定义的异常。例如：

在某种条件抛出异常
```java
  public void test1() throws MyException{   
	...   
  	 if(....){   
    	throw new MyException();  
	 }  
 }

```

### 异常的处理方式

#### 1.在方法中用`try...catch`语句捕获并处理异常，catach语句可以有多个，用来匹配多个异常。
例如：
```java
 public void test2(int x){
   try{    
    	...   
	}catch(Exception e){  
       ...  
   	 }finally{  
	  ...   
	}		  
}

```
#### 2. 对于处理不了的异常或者要转型的异常，在方法的声明处通过`throws`语句抛出异常。定义功能方法时，需要把出现的问题暴露出来让调用者去处理。那么就通过throws在方法上标识。例如：
```java
public void test3() throws MyException{  
	 ...   
	if(....){   
	 throw new MyException();  
	 }  
}

```
#### `throws`和`throw`的区别
#### `throws`:

-  用在方法声明后面，跟的是异常类名

-  可以跟多个异常类名，用逗号隔开

- 表示抛出异常，由该方法的调用者来处理

#### `throw`:

- 用在方法体内，跟的是异常对象名

- 只能抛出一个异常对象名

- 表示抛出异常，由方法体内的语句处理

#### ***如何使用异常处理?***

##### 原则:如果该功能内部可以将问题处理,用`try`,如果处理不了,交由调用者处理,这是用`throws`

#####  区别:

- 后续程序需要继续运行就`try`

- 后续程序不需要继续运行就`throws`

- 如果JDK没有提供对应的异常，需要自定义异常。

####     出现运行时异常后，系统会把异常一直往上层抛，一直遇到处理代码。如果没有处理块，到最上层，如果是多线程就由` Thread.run() `抛出 ，如果是单线程就被 main() 抛出 。抛出之后，如果是线程，这个线程也就退出了。如果是主程序抛出的异常，那么这整个程序也就退出了。运行时异常是 Exception 的子类，也有一般异常的特点，是可以被 Catch 块处理的。只不过往往我们不对他处理罢了。也就是说，你如果不对运行时异常进行处理，那么出现运行时异常之后，要么是线程中止，要么是主程序终止。 如果不想终止，则必须扑捉所有的运行时异常，决不让这个处理线程退出。队列里面出现异常数据了，正常的处理应该是把异常数据舍弃，然后记录日志。不应该由于异常数据而影响下面对正常数据的处理。


### `Throwable`的几个常见方法

- ` getMessage()`获取异常信息，返回字符串。

- `toString()` 获取异常类名和异常信息，返回字符串。

- `printStackTrace`获取异常类名和异常信息，以及异常出现在程序中的位置。返回值void。

```java
public static void main(String[] args) {

	try {
	
	System.out.println(1/0);
	
	} catch (Exception e) {  
     //Exception e = new ArithmeticException("/ by zero");
	
	//System.out.println(e.getMessage());  //获取异常信息
	
	//System.out.println(e); //调用toString方法,打印异常类名和异常信息
	
	e.printStackTrace();  //jvm默认就用这种方式处理异常
	
	  }
	
	}

}

```

### Java异常处理的注意事项

#### 1.避免过大的`try`块，不要把不会出现异常的代码放到try块里面，尽量保持一个try块对应一个或多个异常。  
#### 2.细化异常的类型，不要不管什么类型的异常都写成Excetpion。 
#### 3.`catch`块尽量保持一个块捕获一类异常，不要忽略捕获的异常，捕获到后要么处理，要么转译，要么重新抛出新类型的异常。 
####  4.不要把自己能处理的异常抛给别人。
####  5.当使用多个`catch`语句块来捕获异常时，需要将父类的catch语句块放到子类型的catch块之后，这样才能保证后续的catch可能被执行，否则子类型的catch将永远无法到达，Java编译器会报编译错误。
####  6.如果`try`语句块中存在`return`语句，那么首先会执行`finally`语句块中的代码，然后才返回。

####  7.如果try语句块中存在`System.exit(0)`语句，那么久不会执行finally语句块的代码了，因为`System.exit(0)`会终止当前运行的JVM。程序在JVM终止前结束执行。


